# Generated by Django 4.1.7 on 2023-03-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='Matricule',
            field=models.IntegerField(),
        ),
    ]
